project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Joseph John Cox"
  site-url: https://codensity.io
  description: Operations Research and Manufacturing
  draft-mode: unlinked
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@josephjohncox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - projects.qmd
  page-footer:
    left: "Â© Copyright 2024 Joseph John Cox. All rights reserved."

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true
